### ISSUE TITLE
SLS1 Gnome Settings not detecting touchscreen or stylus

### ISSUE THREAD

**Issue by Ai-Elias** [linux-surface/linux-surface#1440]
[Description of the bug or feature]
I can't seem to be able to get Gnome to recognize my Touchscreen or Stylus on NixOS despite having no issues on Debian. I'm wondering is there is something nix specific that I'm missing here, but I've done quite a bit of digging and the only discrepancy I'm seeing is that libwacom-surface correctly identifies one of the /dev/input/eventXX via the ``libwacom-list-local-devices`` command on Debian but says both are unsupported on NixOS. Maybe I'm failing to properly load a Kernel Module?

### Environment
Hardware model: SLS1 & Slim Pen 2
Kernel version: Linux ibis 6.8.9 #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:35:35 UTC 2024 x86_64 GNU/Linux
Distribution: NixOS 24.11
nixos-hardware modules: microsoft-surface-pro-intel microsoft-surface-common

<details><summary>`dmesg` output</summary>

attached as dmesg.txt as it was too long for github
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/15226999/dmesg.txt)

</details>

**Comment by StollD** [comment]
We don't support NixOS - nobody of us uses it and we don't maintain it's packages. Please report issues to them, as they are the only ones capable of fixing them.

That said, it looks like their libwacom-surface package isn't applying the patch for your device.

* What they apply: https://github.com/NixOS/nixpkgs/blob/f4b6ee7b3f77e4f356e48459158413842cea6d34/pkgs/development/libraries/libwacom/surface.nix#L18-L30
* What we apply: https://github.com/linux-surface/libwacom-surface/tree/v2.10.0-1/patches/v2

**Comment by StollD** [comment]
They aren't different. But we have to patch the libwacom source to support the `virt` bus: https://github.com/linux-surface/libwacom-surface/blob/v2.10.0-1/patches/v2/0001-Add-support-for-BUS_VIRTUAL.patch, so shipping it all as patches is easier.

As long as your libwacom has that patch applied, putting the files in `/etc/libwacom` will work too.

**Comment by Ai-Elias** [comment]
Awesome, thank you! I'll see about opening up a PR with nixpkgs to downstream the patches. Is there any documentation for the .Tablet files that you can point me to? I'd like to understand why some of the options differ in my above examples.

**Comment by Ai-Elias** [comment]
@StollD I've made a little progress on this, after downstreaming 2.10.0 the nixos repo, I am able to get `libwacom-list-local-devices` to identify the device. However gnome settings Wacom Tablet section still doesn't see the touchscreen. Would you happenhave any other troubleshooting advice for me?

`libwacom-list-local-devices` output if relevant. Seems to coincide with the output I was getting on Debian. Thanks in advance!

```
/dev/input/event20 is a tablet but not supported by libwacom
devices:
- name: 'Microsoft Surface Laptop Studio'
  bus: 'unknown'
  vid: '0x045e'
  pid: '0x0c1b'
  nodes: 
  - /dev/input/event23: 'IPTS Stylus'
  styli:
   - id: 0xffffe
     name: 'General Pen Eraser'
     type: 'general'
     axes: ['x', 'y' , 'tilt', 'distance', 'pressure']
     buttons: 2
     is_eraser: 'true'
     eraser_type: 'invert'
   - id: 0xfffff
     name: 'General Pen'
     type: 'general'
     axes: ['x', 'y' , 'tilt', 'distance', 'pressure']
     buttons: 2
     erasers: [0xffffe]
```
